[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"

[tool.mypy]
# __init__.py files are not needed.
explicit_package_bases = true
# Every function must have type hints.
disallow_untyped_defs = true

# Ignore libraries without type hints.
[[tool.mypy.overrides]]
module = [
    "bottle.*",
    "peewee.*",
    "playhouse.*",
]
ignore_missing_imports = true
